services:
  # backend:
  #   image: docker.io/library/onlineshop:0.0.1-SNAPSHOT
  db:
    image: postgres:17
    environment:
      - POSTGRES_DB=onlineshop
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=demo
    ports:
      - 5432:5432
  keycloak:
    image: quay.io/keycloak/keycloak:26.3.2
    ports:
      - 8081:8080
    command:
      - --config-file=/config/keycloak.conf
      - start-dev
    volumes:
      - ./keycloak/keycloak.conf:/config/keycloak.conf
