-- reverse: drop "shopping-carts" table
CREATE TABLE "shopping-carts" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "userid" bigint NULL,
  PRIMARY KEY ("id")
);
-- reverse: create "productpictures" table
DROP TABLE "productpictures";
-- reverse: create "shoppingcarts" table
DROP TABLE "shoppingcarts";
-- reverse: modify "products" table
ALTER TABLE "products" DROP COLUMN "description";
