-- modify "products" table
ALTER TABLE "products" ADD COLUMN "description" character varying(255) NULL;
-- create "shoppingcarts" table
CREATE TABLE "shoppingcarts" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "userid" bigint NULL,
  PRIMARY KEY ("id")
);
-- create "productpictures" table
CREATE TABLE "productpictures" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "product_id" bigint NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "fkjssiyht6ew29kr7682r66lb9x" FOREIGN KEY ("product_id") REFERENCES "products" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION
);
-- drop "shopping-carts" table
DROP TABLE "shopping-carts";
