-- create "products" table
CREATE TABLE "products" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "name" character varying(255) NULL,
  "price" double precision NOT NULL,
  PRIMARY KEY ("id")
);
-- create "shopping-carts" table
CREATE TABLE "shopping-carts" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "userid" bigint NULL,
  PRIMARY KEY ("id")
);
